apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clamds.managed.openshift.io
spec:
  group: managed.openshift.io
  names:
    kind: Clamd
    listKind: ClamdList
    plural: clamds
    singular: clamd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Clamd is the Schema for the clamds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClamdSpec defines the desired state of Clamd
          type: object
        status:
          description: ClamdStatus defines the observed state of Clamd
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
